# permissions for end users to edit customcrds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: customcrd-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kube-builder-crd
    app.kubernetes.io/part-of: kube-builder-crd
    app.kubernetes.io/managed-by: kustomize
  name: customcrd-editor-role
rules:
- apiGroups:
  - batch.tutorial.kubebuilder.io
  resources:
  - customcrds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.tutorial.kubebuilder.io
  resources:
  - customcrds/status
  verbs:
  - get
