apiVersion: batch.tutorial.kubebuilder.io/v1
kind: CustomCrd
metadata:
  labels:
    app.kubernetes.io/name: customcrd
    app.kubernetes.io/instance: customcrd-sample
    app.kubernetes.io/part-of: kube-builder-crd
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kube-builder-crd
  name: customcrd-sample
spec:
  # TODO(user): Add fields here
  deploymentName: "my-deploy"
  replicas: 3
  container:
    image: skaliarman/api-server
    port: 8080
  service:
    erviceName: "my-service"
    serviceType: "NodePort"
    servicePort: 8090
